# vim:ft=kitty

## name:     Rose-Pine (black background)
## author:   rose-pine
## license:  MIT
## upstream: https://github.com/rose-pine/kitty
## blurb:    All natural pine, faux fur and a bit of soho vibes for the classy minimalist.



# The basic colors
foreground              #E0DEF4
background              #000000
selection_foreground    #000000
selection_background    #403D52

# Cursor colors
cursor                  #E0DEF4
cursor_text_color       #000000

# URL underline color when hovering with mouse
url_color               #EBBCBA

# Kitty window border colors
active_border_color     #9CCFD8
inactive_border_color   #6E6A86
bell_border_color       #F6C177

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #000000
active_tab_background   #C4A7E7
inactive_tab_foreground #6E6A86
inactive_tab_background #16141F
tab_bar_background      #000000

# Colors for marks (marked text in the terminal)
mark1_foreground #000000
mark1_background #C4A7E7
mark2_foreground #000000
mark2_background #EBBCBA
mark3_foreground #000000
mark3_background #9CCFD8

# The 16 terminal colors

# black
color0 #26233A
color8 #6E6A86

# red
color1 #EB6F92
color9 #EB6F92

# green
color2  #31748F
color10 #31748F

# yellow
color3  #F6C177
color11 #F6C177

# blue
color4  #9CCFD8
color12 #9CCFD8

# magenta
color5  #C4A7E7
color13 #C4A7E7

# cyan
color6  #EBBCBA
color14 #EBBCBA

# white
color7  #908CAA
color15 #E0DEF4
