# kitty.conf
allow_remote_control yes
listen_on unix:/tmp/kitty

# This looks nice
#background_opacity 0.55
#dynamic_background_opacity yes

background_opacity 1.0
dynamic_background_opacity no

enable_audio_bell no


font_family   JetBrainsMono Nerd Font
font_size     12

#include catppuccin-mocha.conf


# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
