use_nerdfont = true
notify = true
bitrate = 320
cover_max_scale = 2

statusbar_format = "%artists - %title"

[track_format]
left = "%artists - %title"
center = "%album"
right = "%saved %duration"

[theme]
background = "#1e1e2e"
primary = "#cdd6f4"
secondary = "#585b70"
title = "#89b4fa"
playing = "#a6e3a1"
playing_selected = "#1e1e2e"
playing_bg = "#1e1e2e"
highlight = "#1e1e2e"
highlight_bg = "#b4beff"
error = "#1e1e2e"
error_bg = "#f38ba8"
statusbar = "#cdd6f4"
statusbar_progress = "#cdd6f4"
statusbar_bg = "#313244"
cmdline = "#cdd6f4"
cmdline_bg = "#1e1e2e"
search_match = "#f9e2af"
