use_nerdfont = true
notify = true
bitrate = 320
cover_max_scale = 2

statusbar_format = "%artists - %title"

[track_format]
left = "%artists - %title"
center = "%album"
right = "%saved %duration"

[theme]
background = "#000000"
primary = "#e0def4"
secondary = "#403d52"
title = "#9ccfd8"
playing = "#31748f"
playing_selected = "#000000"
playing_bg = "#000000"
highlight = "#000000"
highlight_bg = "#c4a7e7"
error = "#000000"
error_bg = "#eb6f92"
statusbar = "#e0def4"
statusbar_progress = "#e0def4"
statusbar_bg = "#16141f"
cmdline = "#e0def4"
cmdline_bg = "#000000"
search_match = "#f6c177"
